import type { Metadata } from 'next'
import { Poppins, Tilt_Neon } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'


const tilt = Tilt_Neon({
  subsets: ['latin'] ,
  weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={tilt.className}>
        <Navbar />
        <div className='bg-white '>
          {children}
        </div>
        
      </body>
    </html>
  )
}
